site_name: My Docs
plugins:
- search
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- admonition
- pymdownx.details
- pymdownx.superfences
theme:
  name: material
  features:
  - content.code.copy
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.prune
  - navigation.path
  - navigation.top
  palette:
  - scheme: default
    primary: red
    accent: red
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    primary: red
    accent: red
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
nav:
- Home: index.md
- Build Tools:
  - Vite:
    - 001 - CLI: Build Tools/Vite/001 - CLI.md
- CI-CD:
  - GitHub:
    - 001 - Events:
      - 001 - Pull Request: CI-CD/GitHub/001 - Events/001 - Pull Request.md
- Caching:
  - Redis:
    - 001 - Getting Started: Caching/Redis/001 - Getting Started.md
- Cloud:
  - Azure - 204:
    - Azure 204 - Module 01 Revision: Cloud/Azure - 204/Azure 204 - Module 01 Revision.md
    - Azure 204 - Module 02 Revision: Cloud/Azure - 204/Azure 204 - Module 02 Revision.md
    - Azure 204 - Module 03 Revision: Cloud/Azure - 204/Azure 204 - Module 03 Revision.md
    - Azure 204 - Module 04 Revision: Cloud/Azure - 204/Azure 204 - Module 04 Revision.md
    - Azure 204 - Module 05 Revision: Cloud/Azure - 204/Azure 204 - Module 05 Revision.md
    - Azure 204 - Module 06 Revision: Cloud/Azure - 204/Azure 204 - Module 06 Revision.md
    - Azure 204 - Module 07 Revision: Cloud/Azure - 204/Azure 204 - Module 07 Revision.md
    - Azure 204 - Module 08 Revision: Cloud/Azure - 204/Azure 204 - Module 08 Revision.md
    - Azure 204 - Module 09 Revision: Cloud/Azure - 204/Azure 204 - Module 09 Revision.md
    - Azure 204 - Module 10 Revision: Cloud/Azure - 204/Azure 204 - Module 10 Revision.md
    - Azure 204 - Module 11 Revision: Cloud/Azure - 204/Azure 204 - Module 11 Revision.md
    - Azure 204 - Module 12 Revision: Cloud/Azure - 204/Azure 204 - Module 12 Revision.md
    - Exam Notes: Cloud/Azure - 204/Exam Notes.md
- Containerization:
  - Docker:
    - 001 - Dockerfiles:
      - 001 - Reference: Containerization/Docker/001 - Dockerfiles/001 - Reference.md
  - Docker Compose:
    - 001 - Version and name top-level elements: Containerization/Docker Compose/001
        - Version and name top-level elements.md
- Databases:
  - Postgres:
    - 001 - Getting Started: Databases/Postgres/001 - Getting Started.md
- Frameworks:
  - ASP.NET:
    - 01 - Getting Started: Frameworks/ASP.NET/01 - Getting Started.md
  - Django:
    - 998 - Custom Admin Configuration: Frameworks/Django/998 - Custom Admin Configuration.md
    - 999 - Caching with Django: Frameworks/Django/999 - Caching with Django.md
  - Django Ninja:
    - 002- Parsing Input:
      - 001 - HTTP Methods: Frameworks/Django Ninja/002- Parsing Input/001 - HTTP
          Methods.md
  - React:
    - 001 - Quick start: Frameworks/React/001 - Quick start.md
- Languages:
  - C:
    - 01 - Fundamentals:
      - 01 - Hello World: Languages/C/01 - Fundamentals/01 - Hello World.md
      - 02 - Variables and Types: Languages/C/01 - Fundamentals/02 - Variables and
          Types.md
      - 03 - Arrays: Languages/C/01 - Fundamentals/03 - Arrays.md
      - 04 - Multidimensional Arrays: Languages/C/01 - Fundamentals/04 - Multidimensional
          Arrays.md
      - 05 - Conditions: Languages/C/01 - Fundamentals/05 - Conditions.md
      - 06 - Strings: Languages/C/01 - Fundamentals/06 - Strings.md
      - 07 - For loops: Languages/C/01 - Fundamentals/07 - For loops.md
      - 08 - While loops: Languages/C/01 - Fundamentals/08 - While loops.md
      - 09 - Functions: Languages/C/01 - Fundamentals/09 - Functions.md
      - 10 - Static: Languages/C/01 - Fundamentals/10 - Static.md
      - 11 - Pointers: Languages/C/01 - Fundamentals/11 - Pointers.md
      - 12 - Structures: Languages/C/01 - Fundamentals/12 - Structures.md
      - 13 - Function arguments by reference: Languages/C/01 - Fundamentals/13 - Function
          arguments by reference.md
      - 14 - Dynamic allocation: Languages/C/01 - Fundamentals/14 - Dynamic allocation.md
      - 15 - Arrays and pointers: Languages/C/01 - Fundamentals/15 - Arrays and pointers.md
      - 16 - Recursion: Languages/C/01 - Fundamentals/16 - Recursion.md
      - 17 - Linked Lists: Languages/C/01 - Fundamentals/17 - Linked Lists.md
      - 18 - Binary Trees: Languages/C/01 - Fundamentals/18 - Binary Trees.md
      - 19 - Unions: Languages/C/01 - Fundamentals/19 - Unions.md
      - 20 - Pointer Arithmetics: Languages/C/01 - Fundamentals/20 - Pointer Arithmetics.md
      - 21 - Function Pointers: Languages/C/01 - Fundamentals/21 - Function Pointers.md
      - 22 - Bitmasks: Languages/C/01 - Fundamentals/22 - Bitmasks.md
      - 23 - Exercism: Languages/C/01 - Fundamentals/23 - Exercism.md
    - 02 - Data Structures:
      - 1 - Linked Lists: Languages/C/02 - Data Structures/1 - Linked Lists.md
      - 2 - Binary Trees: Languages/C/02 - Data Structures/2 - Binary Trees.md
    - 03 - Pre-processor:
      - 01 - define directives: Languages/C/03 - Pre-processor/01 - define directives.md
      - 02 - Conditional inclusion: Languages/C/03 - Pre-processor/02 - Conditional
          inclusion.md
    - 98 - Exercises:
      - Easy:
        - Binary Search: Languages/C/98 - Exercises/Easy/Binary Search.md
        - Gigasecond: Languages/C/98 - Exercises/Easy/Gigasecond.md
        - Isograms: Languages/C/98 - Exercises/Easy/Isograms.md
        - Robot Simulator: Languages/C/98 - Exercises/Easy/Robot Simulator.md
        - Triangle: Languages/C/98 - Exercises/Easy/Triangle.md
      - Medium:
        - Luhn: Languages/C/98 - Exercises/Medium/Luhn.md
    - 99 - Notes:
      - 01 - General: Languages/C/99 - Notes/01 - General.md
      - 02 - Strings: Languages/C/99 - Notes/02 - Strings.md
      - 03 - Random: Languages/C/99 - Notes/03 - Random.md
      - 04 - Math: Languages/C/99 - Notes/04 - Math.md
  - CSharp:
    - 01 - Getting Started: Languages/CSharp/01 - Getting Started.md
    - 02 - Fundamentals:
      - 01 - Hello World: Languages/CSharp/02 - Fundamentals/01 - Hello World.md
      - 02 - Variables and Types: Languages/CSharp/02 - Fundamentals/02 - Variables
          and Types.md
      - 03 - Type Conversion: Languages/CSharp/02 - Fundamentals/03 - Type Conversion.md
      - 04 - Conditionals: Languages/CSharp/02 - Fundamentals/04 - Conditionals.md
      - 05 - Arrays: Languages/CSharp/02 - Fundamentals/05 - Arrays.md
      - 06 - Lists: Languages/CSharp/02 - Fundamentals/06 - Lists.md
      - 07 - Dictionaries: Languages/CSharp/02 - Fundamentals/07 - Dictionaries.md
    - 03 - Redis:
      - 01 - Getting Started: Languages/CSharp/03 - Redis/01 - Getting Started.md
      - 02 - PubSub with redis: Languages/CSharp/03 - Redis/02 - PubSub with redis.md
  - PHP:
    - 01 - Getting Started: Languages/PHP/01 - Getting Started.md
    - 02 - Fundamentals:
      - 01 - Hello World: Languages/PHP/02 - Fundamentals/01 - Hello World.md
      - 02 - Variables and Types: Languages/PHP/02 - Fundamentals/02 - Variables and
          Types.md
      - 03 - Simple arrays: Languages/PHP/02 - Fundamentals/03 - Simple arrays.md
      - 04 - Arrays with Keys: Languages/PHP/02 - Fundamentals/04 - Arrays with Keys.md
      - 05 - Multidimensional Arrays: Languages/PHP/02 - Fundamentals/05 - Multidimensional
          Arrays.md
      - 06 - Strings: Languages/PHP/02 - Fundamentals/06 - Strings.md
      - 07 - For Loops: Languages/PHP/02 - Fundamentals/07 - For Loops.md
      - 08 - While loops: Languages/PHP/02 - Fundamentals/08 - While loops.md
      - 09 - Functions: Languages/PHP/02 - Fundamentals/09 - Functions.md
      - 10 - Objects: Languages/PHP/02 - Fundamentals/10 - Objects.md
  - Python:
    - 001 - Getting started: Languages/Python/001 - Getting started.md
- Libraries:
  - JS-TS-Node:
    - htmx:
      - 001 - AJAX:
        - 001 - Introduction: Libraries/JS-TS-Node/htmx/001 - AJAX/001 - Introduction.md
  - PHP:
    - Symfony:
      - HTTP Client:
        - 001 - Quick start: Libraries/PHP/Symfony/HTTP Client/001 - Quick start.md
- Package Management:
  - Python:
    - uv:
      - 001 - Getting Started: Package Management/Python/uv/001 - Getting Started.md
      - 002 - Managing python via uv: Package Management/Python/uv/002 - Managing
          python via uv.md
      - 003 - Scripts: Package Management/Python/uv/003 - Scripts.md
      - 004 - Managing Projects:
        - 4.1 - Creating a new project: Package Management/Python/uv/004 - Managing
            Projects/4.1 - Creating a new project.md
        - 4.2 - Creating a new library or package: Package Management/Python/uv/004
            - Managing Projects/4.2 - Creating a new library or package.md
        - 4.3 - Platform restrictions: Package Management/Python/uv/004 - Managing
            Projects/4.3 - Platform restrictions.md
      - 005 - pip compile: Package Management/Python/uv/005 - pip compile.md
      - 999 - Additional resources: Package Management/Python/uv/999 - Additional
          resources.md
- Projects:
  - DockerLens:
    - 000 - DockerLens outline: Projects/DockerLens/000 - DockerLens outline.md
    - 001 - Repository Clean-up: Projects/DockerLens/001 - Repository Clean-up.md
    - 002 - Overview page wireframes: Projects/DockerLens/002 - Overview page wireframes.md
    - 003 - Documentation on initial implementation: Projects/DockerLens/003 - Documentation
        on initial implementation.md
    - 004 - Initial test suite: Projects/DockerLens/004 - Initial test suite.md
    - 005 - General Pipelines: Projects/DockerLens/005 - General Pipelines.md
    - 006 - Release pipelines: Projects/DockerLens/006 - Release pipelines.md
    - 007 - Create more modular twig templates: Projects/DockerLens/007 - Create more
        modular twig templates.md
    - 008 - Update container query endpoint to include all containers: Projects/DockerLens/008
        - Update container query endpoint to include all containers.md
    - 009 - Update table to display the state in different colours: Projects/DockerLens/009
        - Update table to display the state in different colours.md
    - 010 - Cards for different states: Projects/DockerLens/010 - Cards for different
        states.md
    - 011 - Container Detail Page - React FE Setup: Projects/DockerLens/011 - Container
        Detail Page - React FE Setup.md
    - 012 - Container detail page - State card: Projects/DockerLens/012 - Container
        detail page - State card.md
    - 013 - Documentation - Deploy and Update: Projects/DockerLens/013 - Documentation
        - Deploy and Update.md
    - 014 - Container detail page - Restart count card: Projects/DockerLens/014 -
        Container detail page - Restart count card.md
    - 015 - Container detail page - Number of mounts: Projects/DockerLens/015 - Container
        detail page - Number of mounts.md
    - 016 - Container resources endpoint: Projects/DockerLens/016 - Container resources
        endpoint.md
    - 017 - Container resources CPU card: Projects/DockerLens/017 - Container resources
        CPU card.md
    - 018 - Container resources Memory card: Projects/DockerLens/018 - Container resources
        Memory card.md
  - RCL:
    - 001 - Documentation: Projects/RCL/001 - Documentation.md
    - 002 - Side Menu Component: Projects/RCL/002 - Side Menu Component.md
  - RedisPubSub:
    - 001 - Linting: Projects/RedisPubSub/001 - Linting.md
    - 002 - Master - API endpoint to set cache value: Projects/RedisPubSub/002 - Master
        - API endpoint to set cache value.md
  - ShoppingListApp:
    - 001 - Argon2 Password Hashing: Projects/ShoppingListApp/001 - Argon2 Password
        Hashing.md
    - 002 - Store Sorting Parameter: Projects/ShoppingListApp/002 - Store Sorting
        Parameter.md
    - 003 - Stores Custom Admin Configuration: Projects/ShoppingListApp/003 - Stores
        Custom Admin Configuration.md
    - 004 - Item Sorting Parameter: Projects/ShoppingListApp/004 - Item Sorting Parameter.md
    - 005 - Items Custom Admin Configuration: Projects/ShoppingListApp/005 - Items
        Custom Admin Configuration.md
    - 006 - Add filtering to store aggregation API: Projects/ShoppingListApp/006 -
        Add filtering to store aggregation API.md
  - mkdocs-template:
    - 000 - Placeholder: Projects/mkdocs-template/000 - Placeholder.md
  - react-remplate:
    - 001 - Update documentation: Projects/react-remplate/001 - Update documentation.md
    - 002 - Add documentation on workflows: Projects/react-remplate/002 - Add documentation
        on workflows.md
- Proxies:
  - Caddy:
    - 001 - Getting Started: Proxies/Caddy/001 - Getting Started.md
- Roles:
  - Backend:
    - 001 - Internet:
      - 001 - How does the internet work: Roles/Backend/001 - Internet/001 - How does
          the internet work.md
