on:
  push:
    branches:
      - trunk

permissions: write-all

name: Release Please

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          docker build -t documentation:latest .
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push image
        run: |
          docker tag documentation:latest ghcr.io/evanlab02/documentation:latest
          docker push ghcr.io/evanlab02/documentation:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [release]
    defaults:
      run:
        working-directory: ./scripts
    
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "./scripts/.python-version"
      - name: Install the project
        run: uv sync
      - name: Schedule Deployment
        run: uv run deploy.py ${{ secrets.DO_APP_ID }} ${{ secrets.DO_API_SECRET }}
