on:
  push:
    branches:
      - trunk

permissions: write-all

name: Release Please

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "src/uv.lock"

      - name: Install dependencies
        run: |
          uv sync

      - name: Sync Changes
        run: |
          git fetch

      - name: Deploy Documentation
        run: |
          uv run mkdocs gh-deploy --force --no-history
