on:
  push:
    branches:
      - trunk

permissions: write-all

name: Release Please

jobs:
  release-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          docker build -t documentation:latest .
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push image
        run: |
          docker tag documentation:latest ghcr.io/evanlab02/documentation:latest
          docker push ghcr.io/evanlab02/documentation:latest
